import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The Android project is generated by `cap add`/`cap sync` and holds a
    // copy of the built bundle under app/src/main/assets/public -- linting
    // minified output reports errors in code nobody wrote and can't fix.
    "android/**",
  ]),
]);

export default eslintConfig;
